[package]
name = "todo-actix-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "1"
serde = { version = "1", features = ["derive"] }
dotenv = "0.15.0"
config = "0.11.0"
